version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6

    working_directory: ~/geodex
    steps:
      - checkout
      - run:
          name: Installing Dependencies
          command: |
            sudo apt-get update
            sudo pip install -r requirements.txt
            sudo pip install -r requirements-dev.txt
      - run:
          name: Pylint
          command: pylint ~/geodex/geodex --rcfile=~/geodex/.config/pylintrc
      - run:
          name: Unit Tests
          command: python -m unittest -v